[![imagenes/pythonista.png](imagenes/pythonista.png)](https://pythonista.io)

# Tablas.

## Componentes básicos de una tabla.

Una tabla simple es un elemento que contiene una sucesión de filas o renglones, las cuales a su vez contienen una sucesión de celdas.

En la siguiente imagen se muestra:
* Una tabla enmarcada en rojo que contiene 3 filas y cada fila contiene a su vez tres celdas.
* La segunda fila está resaltada en azul.
* La segunda celda de la primera fila está resaltada en verde.

![imagenes/tablas.png](imagenes/tablas.png)

### El elemento ```<table>```.

El elemento ```<table>``` es el contenedor de una tabla.

### Definición de filas con el elemento ```<tr>```.

Cada elemento ```<tr>``` corresponde a la fila horizonta (renglón) de una tabla. Dicho elemento puede contener a una o varias celdas.

### Definición de celdas con el elemento ```<td>```.

El elemento base que conforma a una fila y por ende a una tabla es el elemento ```<td>```. Dicho elemento corresponde a una celda dentro de la tabla. El contendo ```inline``` localizado dentro de las etiquetas de este elemento corresponde al contenidos de la celda. 

```
<td>(contenido inline)</td>
```

Una celda vacía se puede definir con la etiqueta ```<td/>```.

**Ejemplo:**

* El siguiente código creará una tabla con una sola celda.


``` html
<table>
    <td>Hola</td>
</table>
```

Dando por resultado:

<table>
    <td>Hola</td>
</table>

**Ejemplo:**

* El siguiente código creará una tabla de una fila y 3 celdas.


``` html
<table>
    <tr>
        <td>1</td>
        <td>2</td>
        <td>3</td>
    </tr>
</table>
```

Dando por resultado:

<table>
    <tr>
        <td>1</td>
        <td>2</td>
        <td>3</td>
    </tr>
</table>

**Ejemplo:**

* El siguiente código creará una tabla de 3 filas con una sola celda.


``` html
<table>
    <tr>
        <td>1</td>
    </tr>
    <tr>
        <td>2</td>
    </tr>
    <tr>
        <td>3</td>
    </tr>
</table>
```

Dando por resultado:

<table>
    <tr>
        <td>1</td>
    </tr>
    <tr>
        <td>2</td>
    </tr>
    <tr>
        <td>3</td>
    </tr>
</table>

**Ejemplo:**

* El siguiente código creará una tabla conteniendo 3 filas que a su vez contienen 3 celdas en cada fila.

``` html
<table>
    <tr>
        <td>1</td>
        <td>2</td>
        <td>3</td>
    </tr>
    <tr>
        <td>4</td>
        <td>5</td>
        <td>6</td>
    </tr>
    <tr>
        <td>7</td>
        <td>8</td>
        <td>9</td>
    </tr>
</table>
```

Dando por resultado: 

<table>
    <tr>
        <td>1</td>
        <td>2</td>
        <td>3</td>
    </tr>
    <tr>
        <td>4</td>
        <td>5</td>
        <td>6</td>
    </tr>
    <tr>
        <td>7</td>
        <td>8</td>
        <td>9</td>
    </tr>
</table>

**Ejemplo:**

*  No es necesario que las filas tengan el mismo número de celdas, por lo que el siguiente código creará una tabla con 4 filas.
    * La primera fila contiene 2 elementos ```<td>```.
    * La segunda fila contiene 3 elementos ```<td>```.
    * La tercera fila contiene 3 elementos ```<td>```.
    * La cuarta fila contiene 5 elementos ```<td>```.
``` html
<table>
    <tr>
        <td>1</td>  
        <td>2</td>
    </tr>
    <tr>
        <td>3</td>
        <td>4</td>
        <td>5</td>
    </tr>
    <tr>
        <td>6</td>
        <td>7</td>
        <td>8</td>
    </tr>
    <tr>
        <td>9</td>
        <td>10</td>
        <td>11</td>
        <td>12</td>
        <td>13</td>
    </tr>
</table>
```

Dando por resultado:

<table>
    <tr>
        <td>1</td>  
        <td>2</td>
    </tr>
    <tr>
        <td>3</td>
        <td>4</td>
        <td>5</td>
    </tr>
    <tr>
        <td>6</td>
        <td>7</td>
        <td>8</td>
    </tr>
    <tr>
        <td>9</td>
        <td>10</td>
        <td>11</td>
        <td>12</td>
        <td>13</td>
    </tr>
</table>

## Encabezados o índices con ```<th>```.

Los elementos ```<th>```. son similares a los elementos ```<td>```, pero se utilizan para denotar elementos de encabezado o índice en una tabla.

**Ejemplo:**

* El siguiente código define una tabla de 5 filas por 3 columnas.
     * La primera fila contiene elementos ```<th>```.

``` html
<table>
    <tr>
        <th>Primera</th>
        <th>Segunda</th>
        <th>Tercera</th> 
    </tr>
    <tr>
        <td>1</td> 
        <td/> 
        <td>3</td>
    </tr>
    <tr>
        <td>4</td>
        <td>5</td>
        <td>6</td>
    </tr>
    <tr>
        <td>7</td>
        <td>8</td>
        <td>9</td>
    </tr>
    <tr>
        <td>10</td>
        <td>11</td>
        <td>12</td>
    </tr>
</table>
```

Dando por resultado:
<table>
    <tr>
        <th>Uno</th>
        <th>Dos</th>
        <th>Tres</th> 
    </tr>
    <tr>
        <td>1</td> 
        <td/> 
        <td>3</td>
    </tr>
    <tr>
        <td>4</td>
        <td>5</td>
        <td>6</td>
    </tr>
    <tr>
        <td>7</td>
        <td>8</td>
        <td>9</td>
    </tr>
    <tr>
        <td>10</td>
        <td>11</td>
        <td>12</td>
    </tr>
</table>

**Ejemplo:**

* El siguiente código define una tabla de 6 filas por 4 columnas.
    * La primera fila contiene elementos ```<th>```.
    * La primera columna (el primer elemento de cada fila) contiene elementos ```<th>```.

```html
<table>
    <tr>
        <td/><th>Uno</th>
        <th>Dos</th>
        <th>Tres</th> 
    </tr>
    <tr>
        <th>A</th>
        <td>1</td> 
        <td/> 
        <td>3</td>
    </tr>
    <tr>
        <th>B</th>
        <td>4</td>
        <td>5</td>
        <td>6</td>
    </tr>
    <tr>
        <th>C</th>
        <td>7</td>
        <td>8</td>
        <td>9</td>
    </tr>
    <tr>
        <th>D</th>
        <td>10</td>
        <td>11</td>
        <td>12</td>
    </tr>
</table>
```

Dando por resultado:
<table>
    <tr>
        <td/><th>Uno</th>
        <th>Dos</th>
        <th>Tres</th> 
    </tr>
    <tr>
        <th>A</th>
        <td>1</td> 
        <td/> 
        <td>3</td>
    </tr>
    <tr>
        <th>B</th>
        <td>4</td>
        <td>5</td>
        <td>6</td>
    </tr>
    <tr>
        <th>C</th>
        <td>7</td>
        <td>8</td>
        <td>9</td>
    </tr>
    <tr>
        <th>D</th>
        <td>10</td>
        <td>11</td>
        <td>12</td>
    </tr>
</table>

### Atributos ```colspan``` y ```rowspan```.

Es posible extender los elementos ```<td>``` y ```<th>``` a más de una celda.
* El atributo ```colspan``` permite al elemento extenderse hacia la derecha y ocupar el número de celdas ingresadas como valor de este atributo.
* El atributo ```rowspan``` permite al elemento extenderse hacia abajo y ocupar el número de celdas ingresadas como valor de este atributo.

**Ejemplo:**

* El siguiente código creará una tabla de 6 filas por 4 columas.
    * La primera fila corresponde a encabezados.
    * La primera columna corresponde a indices.
    * El primer elemento ```<td>``` de la segunda fila ocupa 2 celdas horizontales (```colspan="2"```).
    * El segundo elemento ```<td>``` de la tercera fila ocupa 4 celdas verticales (```rowspan="4"```).

```html
<table>
    <tr>
        <td/>
        <th>Uno</th>
        <th>Dos</th>
        <th>Tres</th> 
    </tr>
    <tr>
        <th>A</th>
        <td colspan="2">1 extendido</td>
        <td>2</td>
    </tr>
    <tr>
        <th>B</th>
        <td>3</td>
        <td rowspan="4">4<br/>extendido</td>
        <td>5</td>
    </tr>
    <tr>
        <th>C</th>
        <td>6</td>
        <td>7</td>
    </tr>
    <tr>
        <th>D</th>
        <td>8</td>
        <td>9</td>
    </tr>
    <tr>
        <th>E</th>
        <td>10</td>
        <td>11</td>
    </tr>
</table>
```

Dando por resultado:
<table>
    <tr>
        <td/>
        <th>Uno</th>
        <th>Dos</th>
        <th>Tres</th> 
    </tr>
    <tr>
        <th>A</th>
        <td colspan="2">1 extendido</td>
        <td>2</td>
    </tr>
    <tr>
        <th>B</th>
        <td>3</td>
        <td rowspan="4">4<br/>extendido</td>
        <td>5</td>
    </tr>
    <tr>
        <th>C</th>
        <td>6</td>
        <td>7</td>
    </tr>
    <tr>
        <th>D</th>
        <td>8</td>
        <td>9</td>
    </tr>
    <tr>
        <th>E</th>
        <td>10</td>
        <td>11</td>     
    </tr>
</table>

## Estructura de una tabla con ```<thead>```, ```<tbody>```  y ```<tfoot>```.

En HTML5 es posible aplicar una estructura extendida de tabla compuesta por 3 secciones:

* La sección correspondiente al encabezado de una tabla, correspondiente al elemento ```<thead>```.
* La sección correspondiente al cuerpo principal de una tabla, correspondiente al elemento ```<tbody>```.
* La sección correspondiente al pie de una tabla, correspondiente al elemento ```<tfoot>```.

**Ejemplo:**

* El siguiente código creará una tabla de 2 columnas incluyendo:
    * Un elemento ```<thead>``` de una fila compuesta por elementos ```<th>```.
    * Un elemento ```<tbody>``` de 4 filas compuestas por elementos ```<td>```.
    * Un elemento ```<foot>``` de una fila compuesta por elementos ```<th>```.

```html
<table>
    <thead>
        <tr>
            <th>Encabezado 1</th>
            <th>Encabezado 2</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>2</td>
        </tr>
        <tr>
            <td>3</td>
            <td>4</td>
        </tr>
        <tr>
            <td>5</td>
            <td>6</td>
        </tr>
        <tr>
            <td>7</td>
            <td>8</td>
        </tr>
    </tbody>
    <tfoot>
        <tr>
            <th>Pie 1</th>
            <th>Pie 2</th>
        </tr>
    </tfoot>
</table>
```

Dando por resultado:

<table>
    <thead>
        <tr>
            <th>Encabezado 1</th>
            <th>Encabezado 2</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>2</td>
        </tr>
        <tr>
            <td>3</td>
            <td>4</td>
        </tr>
        <tr>
            <td>5</td>
            <td>6</td>
        </tr>
        <tr>
            <td>7</td>
            <td>8</td>
        </tr>
    </tbody>
    <tfoot>
        <tr>
            <th>Pie 1</th>
            <th>Pie 2</th>
        </tr>
    </tfoot>
</table>

## El elemento ```<caption>```.

Este elemento es utilizado para incluir una breve descripción de la tabla y no es parte de la estructura interna de una tabla. Por lo general se coloca por encima del cuerpo de la tabla.

**Ejemplo:**

* El siguiente código creará una tabla de 2 columnas incluyendo:
    * Un elemento ```<caption>```.
    * Un elemento ```<thead>``` de una fila compuesta por elementos ```<th>```.
    * Un elemento ```<tbody>``` de 4 filas compuestas por elementos ```<td>```.
    * Un elemento ```<tfoot>``` de una fila compuesta por elementos ```<th>```.
    
```html
<table>
    <caption>Ejemplo de &lt;caption&gt;.</caption>
    <thead>
        <tr>
            <th>Encabezado 1</th>
            <th>Encabezado 2</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>2</td>
        </tr>
        <tr>
            <td>3</td>
            <td>4</td>
        </tr>
        <tr>
            <td>5</td>
            <td>6</td>
        </tr>
        <tr>
            <td>7</td>
            <td>8</td>
        </tr>
    </tbody>
    <tfoot>
        <tr>
            <th>Pie 1</th>
            <th>Pie 2</th>
        </tr>
    </tfoot>
</table>
```

Dando por resultado:
<table>
    <caption>Ejemplo de &lt;caption&gt;.</caption>
    <thead>
        <tr>
            <th>Encabezado 1</th>
            <th>Encabezado 2</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>1</td>
            <td>2</td>
        </tr>
        <tr>
            <td>3</td>
            <td>4</td>
        </tr>
        <tr>
            <td>5</td>
            <td>6</td>
        </tr>
        <tr>
            <td>7</td>
            <td>8</td>
        </tr>
    </tbody>
    <tfoot>
        <tr>
            <th>Pie 1</th>
            <th>Pie 2</th>
        </tr>
    </tfoot>
</table>

## Documento *HTML* ilustrativo.

El documento [```ejemplos/05_tablas/tablas.html```](ejemplos/05_tablas/tablas.html) contiene el código *HTML* de las celdas de este capítulo.

<p style="text-align: center"><a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Licencia Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a><br />Esta obra está bajo una <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Licencia Creative Commons Atribución 4.0 Internacional</a>.</p>
<p style="text-align: center">&copy; José Luis Chiquete Valdivieso. 2019.</p>